services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  memcached:
    image: memcached:1.6
    command: memcached -m 256
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge